# 前言
pytorch的使用方法，第一章学习的是pytorch中向量的输入，如何将普通数组转化为pytorch中的规定格式的数组。最后实现以下线性规划

# 查看pytorch版本

In [1]:
import torch
print(torch.__version__)

1.4.0


# pytorch中的向量（Tensor）及其生成方式

## 1.随机生成 

In [3]:
random_tensor = torch.rand(3,5)
print(random_tensor)

tensor([[0.9465, 0.3782, 0.7209, 0.2407, 0.0663],
        [0.0568, 0.3566, 0.6090, 0.6453, 0.0935],
        [0.1504, 0.4756, 0.9978, 0.7952, 0.0228]])


## 2.生成全0和全1的矩阵

In [4]:
zero_tensor = torch.zeros(3,5)
print(zero_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
ones_tensor = torch.ones(3,5)
print(ones_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## 3.根据数据直接创建

In [6]:
list = [[1,2,3],
        [4,5,6]]
tensor = torch.tensor(list)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


## 4.Numpy和torch的互相转换

In [8]:
import numpy as np
array = np.array(list)
tensor = torch.from_numpy(array).float()
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
array = tensor.numpy()
print(array)

[[1. 2. 3.]
 [4. 5. 6.]]


注意：tensor转成numpy时，两个向量共用内存，一个改变另一个也会改变；numpy转成tensor时使用的时拷贝，不会同时改变。

# 手写一个线性回归

## 1.如何反向传播和求导

所有的神经网络都需要进行梯度的反向传播和求导，在纸上很容易实现，但是在代码上体现并不容易，如果我们想要进行求导这个操作，可以这样做：

In [10]:
x = torch.tensor([1.],requires_grad=True)
y = x+2
y.backward()
print('y关于x的导数是：{}，y进行的操作是：{}'.format(x.grad, y.grad_fn))

y关于x的导数是：tensor([1.])，y进行的操作是：<AddBackward0 object at 0x0000021F774D6C50>


首先，在变量声明时我们需要告诉计算机，这个变量是需要进行梯度追踪的：requires_grad=True。其次需要让因变量进行反向传播：y.backward()。最终，通过变量.grad()求出导数

## 2.生成数据集

首先生成50个[0,100]内的随机数：

In [14]:
import random
x = []
for i in range(50):
    x.append(round(random.uniform(0,100), 2))
Train_data_x = torch.tensor(x)

真实的直线设定为y=2*x+3，根据这条直线再随机加上一些偏差，模拟数据集。